# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
# orbs:
  # See the Node orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  #  node: circleci/node@5.2

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
jobs:
  npm_run_test:
    docker:
      - image: cimg/node:lts
    resource_class: small
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command:
            - npm run test
          name: Run tests
workflows:
  test_react_app:
    jobs:
      - npm_run_test

