# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/orb-intro/
orbs:
  # See the Node orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@5.2

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
jobs:
  build_image:
    docker:
      - image: cimg/node:lts
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build -t dderyldowney/docker-react:latest -f Dockerfile.dev .
          
  npm_run_test:
    docker:
      - image: dderyldowney/docker-react:latest
    resource_class: small
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
  
  npm_run_build:
    docker:
      - image: dderyldowney/docker-react:latest
    resource_class: small
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: npm run build

  self_hosted_runner:
    docker:
      - image: cimg/base:current
    resource_class: dderyldowney/docker-react
    steps:
      - run: echo "Hi I'm on a Container Runner!"

workflows:
  test_react_app:
    jobs:
      - self_hosted_runner
      - build_image
      - npm_run_test
      - npm_run_build
